/* The count and say sequence is a sequence of numeric strings:
 *
 * 1, 11, 21, 1211, 111221, ...
 *
 * The sequence is generated by writing down the numeric representation of the previous element
 * as we read it aloud.
 *
 * The first element, by definition, is 1.
 *
 * Then, we have:
 *
 * 1 is read as "one 1", so the next element is "11".
 * 11 is read as "two 1s", so the next element is "21".
 * 21 is read as "one 2 [and] one 1", so the next element is "1211".
 * 1211 is read as "one 1 [and] one 2 [and] two 1s", so the next element is "111221".
 * 111221 is read as "three 1s [and] two 2s [and] one 1", so the next element is "312211".
 * ...
 *
 * Write a function to generate the n-th element of this sequence.
 *
 * Source: Careercup (Facebook interview)
 */ 

#include <iostream>
#include <sstream>
#include <vector>

using namespace std;

string count_and_say(unsigned n) {
	if (n == 1) {
		return "1";
	}

	string prev = count_and_say(n-1);
	ostringstream res;

	string::size_type i = 0;
	while (i < prev.size()) {
		string::size_type count = 0;
		while (i+count < prev.size() && prev[i] == prev[i+count]) {
			count++;
		}
		res << count << prev[i];
		i += count;
	}

	return res.str();
}

int main(void) {
	cout << "Enter a value > 0 to get the n-th element of the Count and Say sequence." << endl;
	cout << "> ";

	unsigned n;
	while (cin >> n) {
		cout << count_and_say(n) << endl;
	}

	return 0;
}
